services:
  model-service:
    build:
      context: ./
      dockerfile: ./go/model-service/Dockerfile
    volumes:
      - ./config:/app/model-service/config
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started

  telegram-service:
    build:
      context: ./
      dockerfile: ./go/telegram-service/Dockerfile
    volumes:
      - ./config:/app/telegram-service/config
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: 'postgres:17-alpine'
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d mydatabase -U myuser" ]
      interval: 3s
      timeout: 5s
      retries: 5

  ollama:
    ports:
      - "11434:11434"
    build: ./ollama
    volumes:
      - ./ollama/data:/root/.ollama
    container_name: ollama
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    privileged: true

volumes:
  pg-data:
    name: pg-db-tlb
