[telegram]
TELEGRAM_BOT_TOKEN = "7041264639:AAF6NFMsTXrl79OxjG9HLBhvT-bhnwHMsfM"

[database]
DATABASE_HOST = "хост_базы_данных"
DATABASE_PORT = 5432
DATABASE_USERNAME = "имя_пользователя_базы_данных"
DATABASE_PASSWORD = "пароль_базы_данных"
DATABASE_NAME = "название_базы_данных"

[ollama]
LAMA_COUNT = 10

[server]
SERVER_PORT = 1111